// Generated by gencpp from file yolov3_sort/BoundingBox.msg
// DO NOT EDIT!


#ifndef YOLOV3_SORT_MESSAGE_BOUNDINGBOX_H
#define YOLOV3_SORT_MESSAGE_BOUNDINGBOX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yolov3_sort
{
template <class ContainerAllocator>
struct BoundingBox_
{
  typedef BoundingBox_<ContainerAllocator> Type;

  BoundingBox_()
    : label(0)
    , idx(0)
    , xmin(0.0)
    , ymin(0.0)
    , xmax(0.0)
    , ymax(0.0)  {
    }
  BoundingBox_(const ContainerAllocator& _alloc)
    : label(0)
    , idx(0)
    , xmin(0.0)
    , ymin(0.0)
    , xmax(0.0)
    , ymax(0.0)  {
  (void)_alloc;
    }



   typedef int64_t _label_type;
  _label_type label;

   typedef int64_t _idx_type;
  _idx_type idx;

   typedef double _xmin_type;
  _xmin_type xmin;

   typedef double _ymin_type;
  _ymin_type ymin;

   typedef double _xmax_type;
  _xmax_type xmax;

   typedef double _ymax_type;
  _ymax_type ymax;





  typedef boost::shared_ptr< ::yolov3_sort::BoundingBox_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolov3_sort::BoundingBox_<ContainerAllocator> const> ConstPtr;

}; // struct BoundingBox_

typedef ::yolov3_sort::BoundingBox_<std::allocator<void> > BoundingBox;

typedef boost::shared_ptr< ::yolov3_sort::BoundingBox > BoundingBoxPtr;
typedef boost::shared_ptr< ::yolov3_sort::BoundingBox const> BoundingBoxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolov3_sort::BoundingBox_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolov3_sort::BoundingBox_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::yolov3_sort::BoundingBox_<ContainerAllocator1> & lhs, const ::yolov3_sort::BoundingBox_<ContainerAllocator2> & rhs)
{
  return lhs.label == rhs.label &&
    lhs.idx == rhs.idx &&
    lhs.xmin == rhs.xmin &&
    lhs.ymin == rhs.ymin &&
    lhs.xmax == rhs.xmax &&
    lhs.ymax == rhs.ymax;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::yolov3_sort::BoundingBox_<ContainerAllocator1> & lhs, const ::yolov3_sort::BoundingBox_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace yolov3_sort

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::yolov3_sort::BoundingBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolov3_sort::BoundingBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolov3_sort::BoundingBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolov3_sort::BoundingBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov3_sort::BoundingBox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov3_sort::BoundingBox_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolov3_sort::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "167647b523a0c139be92f837afe9e9e7";
  }

  static const char* value(const ::yolov3_sort::BoundingBox_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x167647b523a0c139ULL;
  static const uint64_t static_value2 = 0xbe92f837afe9e9e7ULL;
};

template<class ContainerAllocator>
struct DataType< ::yolov3_sort::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolov3_sort/BoundingBox";
  }

  static const char* value(const ::yolov3_sort::BoundingBox_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolov3_sort::BoundingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 label\n"
"int64 idx\n"
"float64 xmin\n"
"float64 ymin\n"
"float64 xmax\n"
"float64 ymax\n"
;
  }

  static const char* value(const ::yolov3_sort::BoundingBox_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolov3_sort::BoundingBox_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.label);
      stream.next(m.idx);
      stream.next(m.xmin);
      stream.next(m.ymin);
      stream.next(m.xmax);
      stream.next(m.ymax);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoundingBox_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolov3_sort::BoundingBox_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yolov3_sort::BoundingBox_<ContainerAllocator>& v)
  {
    s << indent << "label: ";
    Printer<int64_t>::stream(s, indent + "  ", v.label);
    s << indent << "idx: ";
    Printer<int64_t>::stream(s, indent + "  ", v.idx);
    s << indent << "xmin: ";
    Printer<double>::stream(s, indent + "  ", v.xmin);
    s << indent << "ymin: ";
    Printer<double>::stream(s, indent + "  ", v.ymin);
    s << indent << "xmax: ";
    Printer<double>::stream(s, indent + "  ", v.xmax);
    s << indent << "ymax: ";
    Printer<double>::stream(s, indent + "  ", v.ymax);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOLOV3_SORT_MESSAGE_BOUNDINGBOX_H
