// Generated by gencpp from file lidar_process/tracked_obj.msg
// DO NOT EDIT!


#ifndef LIDAR_PROCESS_MESSAGE_TRACKED_OBJ_H
#define LIDAR_PROCESS_MESSAGE_TRACKED_OBJ_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>

namespace lidar_process
{
template <class ContainerAllocator>
struct tracked_obj_
{
  typedef tracked_obj_<ContainerAllocator> Type;

  tracked_obj_()
    : header()
    , object_id(0)
    , object_type()
    , point()  {
    }
  tracked_obj_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , object_id(0)
    , object_type(_alloc)
    , point(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _object_id_type;
  _object_id_type object_id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _object_type_type;
  _object_type_type object_type;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _point_type;
  _point_type point;





  typedef boost::shared_ptr< ::lidar_process::tracked_obj_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidar_process::tracked_obj_<ContainerAllocator> const> ConstPtr;

}; // struct tracked_obj_

typedef ::lidar_process::tracked_obj_<std::allocator<void> > tracked_obj;

typedef boost::shared_ptr< ::lidar_process::tracked_obj > tracked_objPtr;
typedef boost::shared_ptr< ::lidar_process::tracked_obj const> tracked_objConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidar_process::tracked_obj_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidar_process::tracked_obj_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lidar_process::tracked_obj_<ContainerAllocator1> & lhs, const ::lidar_process::tracked_obj_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.object_id == rhs.object_id &&
    lhs.object_type == rhs.object_type &&
    lhs.point == rhs.point;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lidar_process::tracked_obj_<ContainerAllocator1> & lhs, const ::lidar_process::tracked_obj_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lidar_process

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lidar_process::tracked_obj_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_process::tracked_obj_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_process::tracked_obj_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_process::tracked_obj_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_process::tracked_obj_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_process::tracked_obj_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidar_process::tracked_obj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a88e8c1fe182ef5a25eeeadb70085b9";
  }

  static const char* value(const ::lidar_process::tracked_obj_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a88e8c1fe182ef5ULL;
  static const uint64_t static_value2 = 0xa25eeeadb70085b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::lidar_process::tracked_obj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidar_process/tracked_obj";
  }

  static const char* value(const ::lidar_process::tracked_obj_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidar_process::tracked_obj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"uint32 object_id\n"
"string object_type\n"
"geometry_msgs/Point point\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::lidar_process::tracked_obj_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidar_process::tracked_obj_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.object_id);
      stream.next(m.object_type);
      stream.next(m.point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct tracked_obj_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidar_process::tracked_obj_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lidar_process::tracked_obj_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "object_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.object_id);
    s << indent << "object_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.object_type);
    s << indent << "point: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.point);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIDAR_PROCESS_MESSAGE_TRACKED_OBJ_H
