// Generated by gencpp from file lidar_process/tracked_obj_arr.msg
// DO NOT EDIT!


#ifndef LIDAR_PROCESS_MESSAGE_TRACKED_OBJ_ARR_H
#define LIDAR_PROCESS_MESSAGE_TRACKED_OBJ_ARR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <lidar_process/tracked_obj.h>

namespace lidar_process
{
template <class ContainerAllocator>
struct tracked_obj_arr_
{
  typedef tracked_obj_arr_<ContainerAllocator> Type;

  tracked_obj_arr_()
    : tracked_obj_arr()  {
    }
  tracked_obj_arr_(const ContainerAllocator& _alloc)
    : tracked_obj_arr(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::lidar_process::tracked_obj_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::lidar_process::tracked_obj_<ContainerAllocator> >::other >  _tracked_obj_arr_type;
  _tracked_obj_arr_type tracked_obj_arr;





  typedef boost::shared_ptr< ::lidar_process::tracked_obj_arr_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lidar_process::tracked_obj_arr_<ContainerAllocator> const> ConstPtr;

}; // struct tracked_obj_arr_

typedef ::lidar_process::tracked_obj_arr_<std::allocator<void> > tracked_obj_arr;

typedef boost::shared_ptr< ::lidar_process::tracked_obj_arr > tracked_obj_arrPtr;
typedef boost::shared_ptr< ::lidar_process::tracked_obj_arr const> tracked_obj_arrConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lidar_process::tracked_obj_arr_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lidar_process::tracked_obj_arr_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lidar_process::tracked_obj_arr_<ContainerAllocator1> & lhs, const ::lidar_process::tracked_obj_arr_<ContainerAllocator2> & rhs)
{
  return lhs.tracked_obj_arr == rhs.tracked_obj_arr;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lidar_process::tracked_obj_arr_<ContainerAllocator1> & lhs, const ::lidar_process::tracked_obj_arr_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lidar_process

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::lidar_process::tracked_obj_arr_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lidar_process::tracked_obj_arr_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_process::tracked_obj_arr_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lidar_process::tracked_obj_arr_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_process::tracked_obj_arr_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lidar_process::tracked_obj_arr_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lidar_process::tracked_obj_arr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "16c935949bd8cf174eedb225267fa459";
  }

  static const char* value(const ::lidar_process::tracked_obj_arr_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x16c935949bd8cf17ULL;
  static const uint64_t static_value2 = 0x4eedb225267fa459ULL;
};

template<class ContainerAllocator>
struct DataType< ::lidar_process::tracked_obj_arr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lidar_process/tracked_obj_arr";
  }

  static const char* value(const ::lidar_process::tracked_obj_arr_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lidar_process::tracked_obj_arr_<ContainerAllocator> >
{
  static const char* value()
  {
    return "tracked_obj[] tracked_obj_arr\n"
"\n"
"================================================================================\n"
"MSG: lidar_process/tracked_obj\n"
"Header header\n"
"uint32 object_id\n"
"string object_type\n"
"geometry_msgs/Point point\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::lidar_process::tracked_obj_arr_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lidar_process::tracked_obj_arr_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tracked_obj_arr);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct tracked_obj_arr_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lidar_process::tracked_obj_arr_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lidar_process::tracked_obj_arr_<ContainerAllocator>& v)
  {
    s << indent << "tracked_obj_arr[]" << std::endl;
    for (size_t i = 0; i < v.tracked_obj_arr.size(); ++i)
    {
      s << indent << "  tracked_obj_arr[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::lidar_process::tracked_obj_<ContainerAllocator> >::stream(s, indent + "    ", v.tracked_obj_arr[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LIDAR_PROCESS_MESSAGE_TRACKED_OBJ_ARR_H
