# General Field Parameters
switch_waypoint_distance: 1
maximum_velocity:         3
safe_distance:            5

waypoint_1: []

waypoint_1: [0.0, 0.0, 5.0]
# waypoint_2: [10.0, 0.0, 1.0]
waypoint_2: [20.0, 0.0, 5.0]

# Orbit Parameters
orbit_freq:               -1
orbit_k_conv:             0.01
heading_k_theta:          1
orbit_change_wait:        4

# Go to Goal Parameters
g2g_sigma:                1.5